name: Build and Publish ASP.NET Core for Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win-x64
          - os: ubuntu-latest
            runtime: linux-x64
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -r ${{ matrix.runtime }} -o ./publish-${{ matrix.runtime }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
         name: app-${{ matrix.runtime }}
         path: ./publish-${{ matrix.runtime }}/
         
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ matrix.runtime }}
        path: ./publish-${{ matrix.runtime }}/
