name: Build and Publish ASP.NET Core for Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        runtime: [win-x64, linux-x64]
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -r ${{ matrix.runtime }} --self-contained true -o ./publish-${{ matrix.runtime }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
         name: app-${{ matrix.runtime }}
         path: ./publish-${{ matrix.runtime }}/
         
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-app
        path: ./publish/
